name: CI

on:
  push:
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pylint
        run: pylint app --fail-under=8

      - name: Run tests
        run: pytest tests -k "not temperature"

      - name: Build Docker image
        run: docker build -t hivebox .
      
      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name hivebox_test hivebox
      
      - name: Test API endpoint
        run: |
          sleep 5
          curl --fail http://localhost:8000/version | grep '"version":"0.0.1"'
      
      - name: Stop Docker container
        run: docker stop hivebox_test